### PR TITLE
make light IDE UI part of the build

### PR DESCRIPTION
**Pull request by akphi**
@pierredebelen In this PR, I setup the build for `legend-pure-ide-light` so that it also do NPM build for the IDE UI. Also, I reconfigure the UI code to read the config from `ideLightConfig.json`. With this setup, the user only needs to build the module and start Dropwizard server, then they can access the editor at `http://localhost:9010/ide` 🍰

### CODE REVIEW

**Comment by akphi** [comment]
@maoo do you know why when I re-push to this PR, the build action is not re-triggered?

**Comment by maoo** [comment]
> @maoo @gs-bracej do you know why when I re-push to this PR, the build action is not re-triggered?

not sure, maybe due to the force-push ? could you try adding a commit?

**Comment by akphi** [comment]
@maoo already did both, nothing happens, only whitesource is rerun

**Comment by akphi** [comment]
@pierredebelen can you try to re-trigger this build? I tried to see if Yarn is available in the pipeline, if not I can take it out.

**Comment by maoo** [comment]
@akphi - thanks for the feedback; I don't have the answer to your question, so I engaged (via email, you're in CC) with our contacts at GitHub; I also found an unanswered thread on https://github.community/t/actions-fail-to-run-on-additional-commits-after-pr-is-created/16302 .

Will keep you posted; in the meantime, please run build actions locally and - optionally - re-run the action manually ( see screenshot below, from the GitHub Actions detail page).

Screenshot 2020-10-26 at 09 55 27

**Comment by akphi** [comment]
@maoo whew, looks like I don't have that option on my `Actions` page

**Comment by maoo** [comment]
> @maoo My bad here. I think I had made a mistake in the build.yml file. Nevertheless, I don't see the option to re-trigger action in github, does it have to do with permission?

Yes, seems that only Write and Maintain roles can re-run the action (see [github docs here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level).

Any maintainer (either legend-wide or per-repo) can re-run the action; maybe you could discuss this with @gs-bracej and @pierredebelen ?

**Comment by akphi** [comment]
@maoo so am I in the `triage` group right now? I don't see this in the doc, but can users with `write` merge PR? If they can't, I might discuss with @pierredebelen  to see if we can give `write` access to some of us.

**Comment by maoo** [comment]
> @maoo so am I in the `triage` group right now?

Yes.

> I don't see this in the doc, but can users with `write` merge PR? If they can't, I might discuss with @pierredebelen to see if we can give `write` access to some of us.

If you become a maintainer of any of the legend repositories, you'd have Maintain access and therefore have the ability to rerun actions (amongst other permissions). I'd suggest to use the existing project entitlements, if possible (that is, maintainer or contributor).

**Pull request merged**
