### PR TITLE
revert dropwizard and jetty upgrade and improve IDE execution perceived performance

### PR DESCRIPTION
**Pull request by akphi**
@aziemchawdhary-gs @kevin-m-knight-gs @pierredebelen it seems like the `dropwizard` and `jetty` upgrade in #36 breaks execution in the IDE. I tried to execute something that takes a long time like `[1:10000]->map(i|print($i);` and the IDE returns me an error. Could you confirm that @aziemchawdhary-gs?

This will certainly make `whitesource` scream, but we might need to workaround that somehow, `dropwizard` is still taking sometimes to port their fix in https://github.com/dropwizard/dropwizard/pull/3522 (and https://github.com/dropwizard/dropwizard/pull/3527) to v1.3.x so we might not be able to wait. I reckon that the best way is to revert this for now. What do you guys think?

### CODE REVIEW

**Comment by aziemchawdhary-gs** [comment]
Yes I see a stack error when executing [1:10000]->map(i|print($i);
Moving back a revision to before the jetty upgrade seems to work fine.

**Comment by akphi** [comment]
@maoo Hey Mao, I notice these guys have sonarcloud bots https://github.com/dropwizard/dropwizard/pull/3527, pretty nice I thought, especially the bug and code-smell part. Is it hard for us to set up one and is this something `legend` folks can help or it has to be from you guys?

**Comment by maoo** [comment]
> Hey @maoo, I notice these guys have [sonarcloud bots](https://github.com/dropwizard/dropwizard/pull/3527#issuecomment-717305627) [dropwizard/dropwizard#3527](https://github.com/dropwizard/dropwizard/pull/3527), pretty nice I thought, especially the bug and code-smell part. Is it hard for us to set up one and is this something `legend` folks can help or it has to be from you guys?

Yes, we can! It's the same integration we have, but we haven't defined quality gates yet. You're an admin of the SonarCloud projects, feel free to play around quality gates and let me know when you're ready to test it.

**Comment by akphi** [comment]
@maoo hm, not sure if I actually am an admin, but I see this `Ask your admin to set a New Code definition.` so I guess not 😭

**Comment by maoo** [comment]
Ok, I upped your permissions, can you plz try now? TY!

Screenshot 2020-10-29 at 09 24 54

**Pull request merged**
